### ISSUE TITLE
join button error

### ISSUE THREAD

**Issue by hy1lite** [itsAPK/Telegram-Referral-Bot#11]
An exception was raised while handling an update
update = {
  "update_id": 836246315,
  "message": {
    "supergroup_chat_created": false,
    "group_chat_created": false,
    "text": "/start",
    "chat": {
      "id": 6331936638,
      "first_name": "Артём",
      "username": "Hy1lite",
      "type": "private"
    },
    "new_chat_photo": [],
    "channel_chat_created": false,
    "delete_chat_photo": false,
    "caption_entities": [],
    "photo": [],
    "message_id": 847,
    "entities": [
      {
        "length": 6,
        "offset": 0,
        "type": "bot_command"
      }
    ],
    "date": 1731094578,
    "new_chat_members": [],
    "from": {
      "language_code": "ru",
      "id": 6331936638,
      "username": "Hy1lite",
      "first_name": "Артём",
      "is_bot": false
    }
  }
}

Traceback (most recent call last):
  File "/home/hy1lite/.local/lib/python3.10/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/hy1lite/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
  File "/home/hy1lite/Telegram-Referral-Bot/src/bot/modules/start.py", line 20, in start
    valid_user(update,context)
  File "/home/hy1lite/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
  File "/home/hy1lite/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 46, in command_func
    if get_contest() == True:
  File "/home/hy1lite/Telegram-Referral-Bot/src/bot/modules/sql/settings_sql.py", line 39, in get_contest
    return contest.contest
AttributeError: 'NoneType' object has no attribute 'contest'

**Comment by hy1lite** [comment]
![{FAB9EDC7-3F0D-4FAE-BF7F-FE0A7A840CD3}](https://github.com/user-attachments/assets/b8462196-e0ee-4d7b-97b8-c8e2c00c85f5)
