### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'contest'

### ISSUE THREAD

**Issue by atatat123** [itsAPK/Telegram-Referral-Bot#13]
Could you help me out please?

Using /startadmin or /start or other commands gives me this error. Would really like to get it to work.
Thanks alot in advance

**Comment by atatat123** [comment]
This is the full error:

 ERROR    [bot] (__main__.py:error_handler:38) Exception while handling an update:
Traceback (most recent call last):

  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
           |    |       |          |       -> {}
           |    |       |          -> ()
           |    |       -> <telegram.ext.callbackcontext.CallbackContext object at 0x7f6120169620>
           |    -> <telegram.update.Update object at 0x7f61205c0f40>
           -> <function start at 0x7f61205e4790>

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/start.py", line 20, in start
    valid_user(update,context)
    |          |      -> <telegram.ext.callbackcontext.CallbackContext object at 0x7f6120169620>
    |          -> <telegram.update.Update object at 0x7f61205c0f40>
    -> <function valid_user at 0x7f61205e4a60>

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
           |    |       |          |       -> {}
           |    |       |          -> ()
           |    |       -> <telegram.ext.callbackcontext.CallbackContext object at 0x7f6120169620>
           |    -> <telegram.update.Update object at 0x7f61205c0f40>
           -> <function valid_user at 0x7f61205e49d0>

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 46, in command_func
    if get_contest() == True:
       -> <function get_contest at 0x7f612055f400>

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/sql/settings_sql.py", line 39, in get_contest
    return contest.contest
           -> None

AttributeError: 'NoneType' object has no attribute 'contest'

**Comment by atatat123** [comment]
When in private chat with the bot and using:

/start

I get the error: invalid user_id specified.

When in the public group chat using:

/start

I get the no contest error(which i assume is because there is no contest yet in the database)

**Comment by atatat123** [comment]
Cant figure out why the user_id is invalid.. because i checked it with my group channel but it is valid. I did not add the @ sign because i see in the code its there.
