### ISSUE TITLE
Invalid user_id specified

### ISSUE THREAD

**Issue by atatat123** [itsAPK/Telegram-Referral-Bot#14]
Hope you can help me out..

Got the right channel in the config:

SUPPORT_CHANNEL='testtestabcd2'

username of the channel is: @testtestabcd2

 but still getting this error;

2024-11-28 17:17:27,631 INFO     [bot] (__main__.py:<module>:67) Successfully loaded modules: ['admin', 'broadcast', 'dashboard', 'leaderboard', 'leave_members', 'settings', 'shill', 'start']
2024-11-28 17:17:27,632 INFO     [bot] (__main__.py:main:62) Using long polling.
2024-11-28 17:17:30,062 ERROR    [bot] (__main__.py:error_handler:38) Exception while handling an update:
Traceback (most recent call last):

  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
           |    |       |          |       -> {}
           |    |       |          -> ()
           |    |       -> <telegram.ext.callbackcontext.CallbackContext object at 0x7f068e3c3a00>
           |    -> <telegram.update.Update object at 0x7f068e3b4400>
           -> <function start at 0x7f068e3d8790>

  File "/home/atnt/python-ref-bot/Telegram-Referral-Bot/src/bot/modules/start.py", line 17, in start
    is_in_grp=context.bot.get_chat_member(f"@{SUPPORT_CHANNEL}",update.effective_message.chat_id)
              |       |                                         |      -> <property object at 0x7f06908c84a0>
              |       |                                         -> <telegram.update.Update object at 0x7f068e3b4400>
              |       -> <property object at 0x7f069001bfb0>
              -> <telegram.ext.callbackcontext.CallbackContext object at 0x7f068e3c3a00>

  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/bot.py", line 3186, in get_chat_member
    result = self._post('getChatMember', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/home/atnt/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)

telegram.error.BadRequest: Invalid user_id specified

**Comment by itsAPK** [comment]
is group is private

**Comment by atatat123** [comment]
No its public, double checked. Hope you can help me out. Will buy you some coffees;)
