### ISSUE TITLE
Object has no attribute 'contest'

### ISSUE THREAD

**Issue by daviesollie** [itsAPK/Telegram-Referral-Bot#4]
When I run the /start command I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
  File "/root/Telegram-Referral-Bot/src/bot/modules/start.py", line 20, in start
    valid_user(update,context)
  File "/root/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
  File "/root/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 46, in command_func
    if get_contest() == True:
  File "/root/Telegram-Referral-Bot/src/bot/modules/sql/settings_sql.py", line 39, in get_contest
    return contest.contest
AttributeError: 'NoneType' object has no attribute 'contest'

Followed all instructions, not missed anything out.

**Comment by itsAPK** [comment]
Click on Start Contest Button on admin

**Comment by hy1lite** [comment]
> Click on Start Contest Button on admin

how click

**Comment by atatat123** [comment]
I get the same, how do i solve this?

**Comment by hy1lite** [comment]
> I get the same, how do i solve this?

nah
