### ISSUE TITLE
telegram.error.BadRequest: User not found

### ISSUE THREAD

**Issue by Zenkaar** [itsAPK/Telegram-Referral-Bot#6]
i followed all the instructions and step but after starting i am getting following error

```
D:\Projects\Telegram referral `bot\Telegram-Referral-Bot-master\Telegram-Referral-Bot-master\src>python` -m bot
2024-06-24 22:28:23,424 INFO     [bot] (__init__.py:<module>:24) Startings
2024-06-24 22:28:23,434 INFO     [bot] (__init__.py:<module>:39) Modules to load: ['admin', 'broadcast', 'dashboard', 'leaderboard', 'leave_members', 'settings', 'shill', 'start']
C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\conversationhandler.py:287: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn(
2024-06-24 22:28:25,825 INFO     [bot] (__main__.py:<module>:67) Successfully loaded modules: ['admin', 'broadcast', 'dashboard', 'leaderboard', 'leave_members', 'settings', 'shill', 'start']
2024-06-24 22:28:25,826 INFO     [bot] (__main__.py:main:62) Using long polling.
2024-06-24 22:28:37,944 ERROR    [bot] (__main__.py:error_handler:38) Exception while handling an update:
Traceback (most recent call last):

  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\utils\promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)

  File "D:\Projects\Telegram referral bot\Telegram-Referral-Bot-master\Telegram-Referral-Bot-master\src\bot\modules\helper_funcs\decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
           |    |       |          |       -> {}
           |    |       |          -> ()
           |    |       -> <telegram.ext.callbackcontext.CallbackContext object at 0x0000029161C00F90>
           |    -> <telegram.update.Update object at 0x0000029161BE7A00>
           -> <function start at 0x0000029161C135E0>

  File "D:\Projects\Telegram referral bot\Telegram-Referral-Bot-master\Telegram-Referral-Bot-master\src\bot\modules\start.py", line 16, in start
    is_in_grp=context.bot.get_chat_member(f"@{SUPPORT_CHANNEL}",update.effective_message.chat_id)
              |       |                                         |      -> <property object at 0x000002915E347AE0>
              |       |                                         -> <telegram.update.Update object at 0x0000029161BE7A00>
              |       -> <property object at 0x0000029160209E00>
              -> <telegram.ext.callbackcontext.CallbackContext object at 0x0000029161C00F90>

  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\bot.py", line 3186, in get_chat_member
    result = self._post('getChatMember', data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "C:\Users\Miniv\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)

telegram.error.BadRequest: User not found

An uncaught error was raised while handling the error.
```
can you suggest how to resolve it??

**Comment by itsAPK** [comment]
replace your support channel username in SUPPORT_CHANNEL in config.py

**Comment by itsAPK** [comment]
SUPPORT_CHANNEL='' #Channel where referal users need to join

**Comment by Zenkaar** [comment]
Thanks @itsAPK for your prompt response, just solved this issue by make tg group public and by feeding group link

**Comment by Zenkaar** [comment]
closing this issue

**Comment by bsgarcia** [comment]
Hi, sorry for bumping this closed issue. 

I get a similar exception (it says "invalid user_id" instead of "not found") at the exact same line. I applied @Zenkaar solution but I still get the error. 

My procedure: 

I set the SUPPORT_CHANNEL to the group username. e.g.  PC Games Support  username would be pc_game_down_support (https://t.me/pc_game_down_support).  The group is public.

Then I add my bot as administrator in the tg group. Then I use the '/start' command. Following this I get this error:

 ```
→ python -m bot
2024-08-16 01:44:00,948 INFO     [bot] (__init__.py:<module>:24) Startings
2024-08-16 01:44:00,950 INFO     [bot] (__init__.py:<module>:39) Modules to load: ['admin', 'broadcast', 'dashboard', 'leaderboard', 'leave_members', 'settings', 'shill', 'start']
/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/ext/conversationhandler.py:287: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn(
2024-08-16 01:44:01,185 INFO     [bot] (__main__.py:<module>:67) Successfully loaded modules: ['admin', 'broadcast', 'dashboard', 'leaderboard', 'leave_members', 'settings', 'shill', 'start']
2024-08-16 01:44:01,185 INFO     [bot] (__main__.py:main:62) Using long polling.
2024-08-16 01:44:08,842 ERROR    [bot] (__main__.py:error_handler:38) Exception while handling an update:
Traceback (most recent call last):

  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)

  File "/home/bsgarcia/bots/Telegram-Referral-Bot/src/bot/modules/helper_funcs/decorators.py", line 18, in command_func
    return func(update, context,  *args, **kwargs)
           |    |       |          |       -> {}
           |    |       |          -> ()
           |    |       -> <telegram.ext.callbackcontext.CallbackContext object at 0x7fd7ab9a7200>
           |    -> <telegram.update.Update object at 0x7fd7ab98e4c0>
           -> <function start at 0x7fd7ab990940>


 File "/home/bsgarcia/bots/Telegram-Referral-Bot/src/bot/modules/start.py", line 16, in start
    is_in_grp=context.bot.get_chat_member(f"@{SUPPORT_CHANNEL}",update.effective_message.chat_id)
              |       |                                         |      -> <property object at 0x7fd7aeb6cae0>
              |       |                                         -> <telegram.update.Update object at 0x7fd7ab98e4c0>
              |       -> <property object at 0x7fd7ae496220>
              -> <telegram.ext.callbackcontext.CallbackContext object at 0x7fd7ab9a7200>

  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 3186, in get_chat_member
    result = self._post('getChatMember', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/home/bsgarcia/bots/Telegram-Referral-Bot/.venv/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)

telegram.error.BadRequest: Invalid user_id specified
```

**Comment by atatat123** [comment]
I have this same issue, invalid user_id specified. Did you found any solutions?

**Comment by atatat123** [comment]
@bsgarcia did you solve your issue? I got the same
